In [2]:
!pip install psycopg2

Collecting psycopg2
  Downloading psycopg2-2.9.3.tar.gz (380 kB)
     |████████████████████████████████| 380 kB 5.6 MB/s eta 0:00:01     |███████████████▌                | 184 kB 5.6 MB/s eta 0:00:01
Building wheels for collected packages: psycopg2
  Building wheel for psycopg2 (setup.py) ... done
  Created wheel for psycopg2: filename=psycopg2-2.9.3-cp38-cp38-linux_x86_64.whl size=554147 sha256=71d9fffe6e45ade72fa3ad7ead097ece8856a6408aee47af3d8b6633e2e9ce5a
  Stored in directory: /tmp/pip-ephem-wheel-cache-_6337o63/wheels/f3/dc/e2/b8e0e2142eff7fd680295ecd2d92e3bfbb90195523e43da161
Successfully built psycopg2
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.3
WARNING: You are using pip version 21.2.4; however, version 22.0.4 is available.
You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.

In [6]:
import psycopg2
conn = psycopg2.connect(
    host="pg-flights-data",
    database="postgres",
    user="postgres",
    password="postgres")

# Opens a cursur that you can use to execute SQL commands
cursor = conn.cursor()
cursor.execute("Select count(1) from flights;")
# Retrieve one record from the stream
cursor.fetchone()

(5819079,)

In [7]:
!pip install pandas

Collecting pandas
  Downloading pandas-1.4.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
     |████████████████████████████████| 11.7 MB 2.9 MB/s eta 0:00:01    |████████████                    | 4.4 MB 2.9 MB/s eta 0:00:03
Requirement already satisfied: pytz>=2020.1 in /opt/app-root/lib/python3.8/site-packages (from pandas) (2021.1)
Collecting numpy>=1.18.5
  Downloading numpy-1.22.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     |████████████████████████████████| 16.8 MB 15.4 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/app-root/lib/python3.8/site-packages (from pandas) (2.8.1)
Requirement already satisfied: six>=1.5 in /opt/app-root/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas) (1.15.0)
Installing collected packages: numpy, pandas
Successfully installed numpy-1.22.3 pandas-1.4.1
WARNING: You are using pip version 21.2.4; however, version 22.0.4 is available.
You should consider upgrading via the '/opt/app-root/bin/python3.8 -m pip install --upgrade pip' command.

In [8]:
import psycopg2
import pandas as pds
from sqlalchemy import create_engine

alchemy_engine = create_engine('postgresql+psycopg2://postgres:postgres@pg-flights-data/postgres')
conn = alchemy_engine.connect()
dataFrame = pds.read_sql("select * from flights limit 10;", conn)
print(dataFrame)
conn.close()

   year  month  day  day_of_week airline  flight_number tail_number  \
0  2015      1    1            4      AS             98      N407AS
1  2015      1    1            4      AA           2336      N3KUAA
2  2015      1    1            4      US            840      N171US
3  2015      1    1            4      AA            258      N3HYAA
4  2015      1    1            4      AS            135      N527AS
5  2015      1    1            4      DL            806      N3730B
6  2015      1    1            4      NK            612      N635NK
7  2015      1    1            4      US           2013      N584UW
8  2015      1    1            4      AA           1112      N3LAAA
9  2015      1    1            4      DL           1173      N826DN

  origin_airport destination_airport scheduled_departure  ... arrival_time  \
0            ANC                 SEA                0005  ...         0408
1            LAX                 PBI                0010  ...         0741
2            SFO                 CLT                0020  ...         0811
3            LAX                 MIA                0020  ...         0756
4            SEA                 ANC                0025  ...         0259
5            SFO                 MSP                0025  ...         0610
6            LAS                 MSP                0025  ...         0509
7            LAX                 CLT                0030  ...         0753
8            SFO                 DFW                0030  ...         0532
9            LAS                 ATL                0030  ...         0656

   arrival_delay  diverted cancelled  cancellation_reason  air_system_delay  \
0            -22         0         0                 None              None
1             -9         0         0                 None              None
2              5         0         0                 None              None
3             -9         0         0                 None              None
4            -21         0         0                 None              None
5              8         0         0                 None              None
6            -17         0         0                 None              None
7            -10         0         0                 None              None
8            -13         0         0                 None              None
9            -15         0         0                 None              None

   security_delay  airline_delay late_aircraft_delay  weather_delay
0            None           None                None           None
1            None           None                None           None
2            None           None                None           None
3            None           None                None           None
4            None           None                None           None
5            None           None                None           None
6            None           None                None           None
7            None           None                None           None
8            None           None                None           None
9            None           None                None           None

[10 rows x 31 columns]

In [13]:
import os
from pyspark.sql import SparkSession

os.environ['PYSPARK_SUBMIT_ARGS'] = "\
--packages org.apache.hadoop:hadoop-aws:3.2.0,org.postgresql:postgresql:42.3.3 \
--master spark://" + os.environ['SPARK_CLUSTER'] + ":7077 pyspark-shell "

# Create the spark application
spark = SparkSession \
    .builder \
    .appName("Python Spark SQL basic example") \
    .getOrCreate()

df = spark.read \
    .format("jdbc") \
    .option("url", "jdbc:postgresql://pg-flights-data:5432/postgres") \
    .option("dbtable", "flights") \
    .option("user", "postgres") \
    .option("password", "postgres") \
    .option("driver", "org.postgresql.Driver") \
    .option("numPartitions", 31) \
    .option("partitionColumn", "day") \
    .option("lowerBound", 0) \
    .option("upperBound", 32) \
    .load()

df.show(5)
df.printSchema()
spark.stop()

+----+-----+---+-----------+-------+-------------+-----------+--------------+-------------------+-------------------+--------------+---------------+--------+----------+--------------+------------+--------+--------+---------+-------+-----------------+------------+-------------+--------+---------+-------------------+----------------+--------------+-------------+-------------------+-------------+
|year|month|day|day_of_week|airline|flight_number|tail_number|origin_airport|destination_airport|scheduled_departure|departure_time|departure_delay|taxi_out|wheels_off|scheduled_time|elapsed_time|air_time|distance|wheels_on|taxi_in|scheduled_arrival|arrival_time|arrival_delay|diverted|cancelled|cancellation_reason|air_system_delay|security_delay|airline_delay|late_aircraft_delay|weather_delay|
+----+-----+---+-----------+-------+-------------+-----------+--------------+-------------------+-------------------+--------------+---------------+--------+----------+--------------+------------+--------+--------+---------+-------+-----------------+------------+-------------+--------+---------+-------------------+----------------+--------------+-------------+-------------------+-------------+
|2015|    1|  1|          4|     US|         2064|     N538UW|           DFW|                CLT|               0700|          0655|             -5|      35|      0730|           148|         155|     112|     936|     1022|      8|             1028|        1030|            2|       0|        0|               null|            null|          null|         null|               null|         null|
|2015|    1|  1|          4|     UA|          463|     N482UA|           LGA|                ORD|               0700|          0658|             -2|      13|      0711|           159|         156|     136|     733|     0827|      7|             0839|        0834|           -5|       0|        0|               null|            null|          null|         null|               null|         null|
|2015|    1|  1|          4|     UA|          514|     N411UA|           BOS|                IAH|               0700|          0656|             -4|      15|      0711|           273|         261|     236|    1597|     1007|     10|             1033|        1017|          -16|       0|        0|               null|            null|          null|         null|               null|         null|
|2015|    1|  1|          4|     UA|          521|     N854UA|           BOS|                ORD|               0700|          0700|              0|      32|      0732|           178|         191|     154|     867|     0906|      5|             0858|        0911|           13|       0|        0|               null|            null|          null|         null|               null|         null|
|2015|    1|  1|          4|     UA|          736|     N522UA|           SFO|                EWR|               0700|          0659|             -1|      21|      0720|           326|         315|     286|    2565|     1506|      8|             1526|        1514|          -12|       0|        0|               null|            null|          null|         null|               null|         null|
+----+-----+---+-----------+-------+-------------+-----------+--------------+-------------------+-------------------+--------------+---------------+--------+----------+--------------+------------+--------+--------+---------+-------+-----------------+------------+-------------+--------+---------+-------------------+----------------+--------------+-------------+-------------------+-------------+
only showing top 5 rows

root
 |-- year: integer (nullable = true)
 |-- month: integer (nullable = true)
 |-- day: integer (nullable = true)
 |-- day_of_week: integer (nullable = true)
 |-- airline: string (nullable = true)
 |-- flight_number: integer (nullable = true)
 |-- tail_number: string (nullable = true)
 |-- origin_airport: string (nullable = true)
 |-- destination_airport: string (nullable = true)
 |-- scheduled_departure: string (nullable = true)
 |-- departure_time: string (nullable = true)
 |-- departure_delay: integer (nullable = true)
 |-- taxi_out: integer (nullable = true)
 |-- wheels_off: string (nullable = true)
 |-- scheduled_time: integer (nullable = true)
 |-- elapsed_time: integer (nullable = true)
 |-- air_time: integer (nullable = true)
 |-- distance: integer (nullable = true)
 |-- wheels_on: string (nullable = true)
 |-- taxi_in: integer (nullable = true)
 |-- scheduled_arrival: string (nullable = true)
 |-- arrival_time: string (nullable = true)
 |-- arrival_delay: integer (nullable = true)
 |-- diverted: integer (nullable = true)
 |-- cancelled: integer (nullable = true)
 |-- cancellation_reason: string (nullable = true)
 |-- air_system_delay: integer (nullable = true)
 |-- security_delay: integer (nullable = true)
 |-- airline_delay: integer (nullable = true)
 |-- late_aircraft_delay: integer (nullable = true)
 |-- weather_delay: integer (nullable = true)

In [2]:
import os
from pyspark.sql import SparkSession


os.environ['PYSPARK_SUBMIT_ARGS'] = f"\
--conf spark.hadoop.fs.s3a.endpoint=http://minio-ml-workshop:9000 \
--conf spark.hadoop.fs.s3a.access.key=minio \
--conf spark.hadoop.fs.s3a.secret.key=minio123 \
--conf spark.hadoop.fs.s3a.path.style.access=true \
--conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem \
--conf spark.hadoop.fs.s3a.multipart.size=104857600 \
--packages org.apache.hadoop:hadoop-aws:3.2.0,org.postgresql:postgresql:42.3.3 \
--master spark://{os.environ['SPARK_CLUSTER']}:7077 pyspark-shell "

# Create the spark application
spark = SparkSession \
    .builder \
    .appName("Python Spark S3 example") \
    .getOrCreate()

dfAirlines = spark.read\
                .options(delimeter=',', inferSchema='True', header='True') \
                .csv("s3a://airport-data/airlines.csv")
dfAirlines.printSchema()

dfAirports = spark.read\
                .options(delimiter=',', inferSchema='True', header='True') \
                .csv("s3a://airport-data/airports.csv")
dfAirports.printSchema()

dfAirports.show(truncate=False)
dfAirlines.show(truncate=False)

print(dfAirports.count())
print(dfAirlines.count())

spark.stop()

root
 |-- IATA_CODE: string (nullable = true)
 |-- AIRLINE: string (nullable = true)

root
 |-- IATA_CODE: string (nullable = true)
 |-- AIRPORT: string (nullable = true)
 |-- CITY: string (nullable = true)
 |-- STATE: string (nullable = true)
 |-- COUNTRY: string (nullable = true)
 |-- LATITUDE: double (nullable = true)
 |-- LONGITUDE: double (nullable = true)

+---------+-------------------------------------------+-------------+-----+-------+--------+----------+
|IATA_CODE|AIRPORT                                    |CITY         |STATE|COUNTRY|LATITUDE|LONGITUDE |
+---------+-------------------------------------------+-------------+-----+-------+--------+----------+
|ABE      |Lehigh Valley International Airport        |Allentown    |PA   |USA    |40.65236|-75.4404  |
|ABI      |Abilene Regional Airport                   |Abilene      |TX   |USA    |32.41132|-99.6819  |
|ABQ      |Albuquerque International Sunport          |Albuquerque  |NM   |USA    |35.04022|-106.60919|
|ABR      |Aberdeen Regional Airport                  |Aberdeen     |SD   |USA    |45.44906|-98.42183 |
|ABY      |Southwest Georgia Regional Airport         |Albany       |GA   |USA    |31.53552|-84.19447 |
|ACK      |Nantucket Memorial Airport                 |Nantucket    |MA   |USA    |41.25305|-70.06018 |
|ACT      |Waco Regional Airport                      |Waco         |TX   |USA    |31.61129|-97.23052 |
|ACV      |Arcata Airport                             |Arcata/Eureka|CA   |USA    |40.97812|-124.10862|
|ACY      |Atlantic City International Airport        |Atlantic City|NJ   |USA    |39.45758|-74.57717 |
|ADK      |Adak Airport                               |Adak         |AK   |USA    |51.87796|-176.64603|
|ADQ      |Kodiak Airport                             |Kodiak       |AK   |USA    |57.74997|-152.49386|
|AEX      |Alexandria International Airport           |Alexandria   |LA   |USA    |31.32737|-92.54856 |
|AGS      |Augusta Regional Airport (Bush Field)      |Augusta      |GA   |USA    |33.36996|-81.9645  |
|AKN      |King Salmon Airport                        |King Salmon  |AK   |USA    |58.6768 |-156.64922|
|ALB      |Albany International Airport               |Albany       |NY   |USA    |42.74812|-73.80298 |
|ALO      |Waterloo Regional Airport                  |Waterloo     |IA   |USA    |42.55708|-92.40034 |
|AMA      |Rick Husband Amarillo International Airport|Amarillo     |TX   |USA    |35.21937|-101.70593|
|ANC      |Ted Stevens Anchorage International Airport|Anchorage    |AK   |USA    |61.17432|-149.99619|
|APN      |Alpena County Regional Airport             |Alpena       |MI   |USA    |45.07807|-83.56029 |
|ASE      |Aspen-Pitkin County Airport                |Aspen        |CO   |USA    |39.22316|-106.86885|
+---------+-------------------------------------------+-------------+-----+-------+--------+----------+
only showing top 20 rows

+---------+----------------------------+
|IATA_CODE|AIRLINE                     |
+---------+----------------------------+
|UA       |United Air Lines Inc.       |
|AA       |American Airlines Inc.      |
|US       |US Airways Inc.             |
|F9       |Frontier Airlines Inc.      |
|B6       |JetBlue Airways             |
|OO       |Skywest Airlines Inc.       |
|AS       |Alaska Airlines Inc.        |
|NK       |Spirit Air Lines            |
|WN       |Southwest Airlines Co.      |
|DL       |Delta Air Lines Inc.        |
|EV       |Atlantic Southeast Airlines |
|HA       |Hawaiian Airlines Inc.      |
|MQ       |American Eagle Airlines Inc.|
|VX       |Virgin America              |
+---------+----------------------------+

322
14